name: OpenSSF Scorecard

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday

permissions:
  id-token: write
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload scorecard results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
